### ISSUE TITLE
Error : torch_sparse/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

### ISSUE THREAD

**Issue by vas2201** [wentaoveggiebird/Siamese-MoNet#20]
After installation of dependencies  ... I am training the model Graphsite-classifier.   getting the following error.
Please advise on this matter ..
Thank you

Traceback (most recent call last):
  File "/home/nmrbox/spenumutchu/workflow2023/56Graphsite_classifer/Graphsite-classifier-master/gnn/train_classifier.py", line 8, in <module>
    from dataloader import read_cluster_file_from_yaml
  File "/home/nmrbox/spenumutchu/workflow2023/56Graphsite_classifer/Graphsite-classifier-master/gnn/dataloader.py", line 6, in <module>
    from torch_geometric.data import Data, Dataset
  File "/home/nmrbox/spenumutchu/anaconda3/envs/56Graphsite-classifier_py37/lib/python3.9/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/nmrbox/spenumutchu/anaconda3/envs/56Graphsite-classifier_py37/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/nmrbox/spenumutchu/anaconda3/envs/56Graphsite-classifier_py37/lib/python3.9/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/home/nmrbox/spenumutchu/anaconda3/envs/56Graphsite-classifier_py37/lib/python3.9/site-packages/torch_sparse/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/nmrbox/spenumutchu/anaconda3/envs/56Graphsite-classifier_py37/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/home/nmrbox/spenumutchu/anaconda3/envs/56Graphsite-classifier_py37/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/nmrbox/spenumutchu/anaconda3/envs/56Graphsite-classifier_py37/lib/python3.9/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

**Comment by vas2201** [comment]
"Could you kindly provide me with information on which versions of PyTorch and torch-geometric are compatible with the code that you have compiled?"
These are the current dependencies that I installed. 
channels:
  - conda-forge
  - defaults
  - https://levinthal:paradox@conda.rosettacommons.org
  - bioconda
  - pytorch
  - dglteam
  - anaconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - liblapack=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - numpy=1.24.1=py39h223a676_0
  - openssl=3.0.7=h0b41bf4_1
  - pip=22.3.1=pyhd8ed1ab_0
  - python=3.9.15=hba424b6_0_cpython
  - python_abi=3.9=3_cp39
  - readline=8.1.2=h0f457ee_0
  - setuptools=65.6.3=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2022g=h191b570_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - biopandas==0.4.1
      - charset-normalizer==2.1.1
      - contourpy==1.0.6
      - cycler==0.11.0
      - fonttools==4.38.0
      - googledrivedownloader==0.4
      - h5py==3.7.0
      - idna==3.4
      - isodate==0.6.1
      - jinja2==3.1.2
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - markupsafe==2.1.1
      - matplotlib==3.6.2
      - networkx==2.8.8
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - packaging==22.0
      - pandas==1.5.2
      - pillow==9.4.0
      - plyfile==0.7.4
      - psutil==5.9.4
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-louvain==0.16
      - pytz==2022.7
      - pyyaml==6.0
      - rdflib==6.2.0
      - requests==2.28.1
      - scikit-learn==1.2.0
      - scipy==1.9.3
      - six==1.16.0
      - threadpoolctl==3.1.0
      - torch==1.8.1
      - torch-geometric==2.2.0
      - torch-scatter==2.1.0
      - torch-sparse==0.6.16
      - torchmetrics==0.11.0
      - tqdm==4.64.1
      - typing-extensions==4.4.0
      - urllib3==1.26.13

**Comment by vas2201** [comment]
It appears that there is a disagreement between the GPU and CPU versions of some dependencies. Both conda and pip are installing both versions (pytorch), which is causing the error. If anyone has a solution to this problem, please let me know. Thank you for your assistance.

**Comment by vas2201** [comment]
this issue is resolved. TQ
